### ISSUE TITLE
AWS Region Issue with Fog dependency > 1.24.0

### ISSUE THREAD

**Issue by epantera** [snowplow/sluice#32]
Hello there,

there a an AWS Region issue with Fog >= 1.25.0 - [#3275](https://github.com/fog/fog/issues/3275).
The current Sluice Gemfile define a dependency on Fog >= 1.22.0

So we just face the Region Issue here after upgrading our Snowplow EMR-RUNNER version.

As a temporary workaround we enrich the emr-etl-runner Gemfile to add a Fog dependency sticked to the 1.24.0 version.

What do you think about updating Sluice Gemfile to stick to Fog 1.24.0 until a proper integration ?

Cheers,

**Comment by alexanderdean** [comment]
Hey @epantera - I think that's a good idea definitely. Do you want to submit a PR? We'll update the next versions of EmrEtlRunner and StorageLoader to use this next release of Sluice.
